service_name: my-service
http:
  port: 3000
simple:
  get: Hello World
db:
  type: postgres
  host: localhost
  port: 9432
  username: postgres
  password: password
  database: my_database
redis:
  host: localhost
  port: 9379
cached:
  ttlInSeconds: 60
kafka:
  broker_host: localhost
  broker_port: 9092
  group: my-service-group
  retries: 0
  consumerSessionTimeout: 480000
  consumerHeartbeatInterval: 3000
  consumerMaxWaitTimeInMs: 100
