http:
  port: 3000
simple:
  get: Hello World
db:
  type: postgres
  host: localhost
  port: 9432
  username: postgres
  password: password
  database: my_database
redis:
  host: localhost
  port: 9379
cached:
  ttlInSeconds: 60
